### ISSUE TITLE
Sync presenter and participant screen

### ISSUE THREAD

**Issue by subhojit777** [subhojit777/questionnaire-backend#40]
## Motivation

Websocket is required to sync presenter and the participant screen.

## Technical specs

The data used during the communication should have:

`presentation_id` - the id of the presentation which is being presented
`question_index` - the index position of the question to be shown in presenter and participant screen

All questions for a presentation need to be fetched, and get the count, and that is how the `question_index` will be decided. It should not be less than 0, and should not exceed the (number of questions - 1)

We need to make sure that the query for http://subhojit777.in/questionnaire-backend/questionnaire_rs/index.html#get-questions-for-a-presentation returns the questions in same order as for `question_index`

## Tasks

- [x] On WebSocket request send the next `question_index`
	- [x] Create a listener that recieves the data, and echoes the message
	- [x] Improvise the echo message, and send the next `question_index`

## Notes

Doc can be found here https://actix.rs/docs/websockets/ it also has links to examples

React WebSocket example https://blog.logrocket.com/websockets-tutorial-how-to-go-real-time-with-node-and-react-8e4693fbf843
