### ISSUE TITLE
Sync presenter and participant screen - part 2

### ISSUE THREAD

**Issue by subhojit777** [subhojit777/questionnaire-backend#43]
### Motivation

When participant has answered a question, the chart in presenter's screen should be updated automatically.

### Tasks

- [x] New `enum` called `event`
	- Values
		- [x] `navigate`
		- [x] `answers.create`
- [x] Make room for the new communication event
	- `trait` implementation of the various communication event
		- [x] `response` method for attaching event specific data to the socket response
	- [x] Include an `event` in the existing `WebSocketResponse`
	- [x] Include an `event` in the existing `WebSocketRequest`
	- [x] Add `event` as `navigate` for the existing response
- [x] Sync the screens
	- [x] New request type for `answers.create`
		- Update `new_answer` so that it returns the newly created answer
		- `AnswersCreateRequest` struct containing - `option_id: i32`, `user_id: i32`
	- [x] New response type for `answers.create`, maybe use `trait`
		- `AnswersCreateResponse` struct containing - `data: Answer`
	- [x] Send the answer as response when it is created
